instr_ref= {
"const_int":{'dest': 'a', 'op': 'const', 'type': 'int', 'value': 1} ,
"const_bool":{'dest': 'cond', 'op': 'const', 'type': 'bool', 'value': True} ,
"add":{'args': ['x', 'y'], 'dest': 'w', 'op': 'add', 'type': 'int'} ,
"sub":{'args': ['vali', 'valn'], 'dest': 'sub_0', 'op': 'sub', 'type': 'int'} ,
"mul":{'args': ['out', 'base'], 'dest': 'out', 'op': 'mul', 'type': 'int'} ,
"div":{'args': ['v13', 'v14'], 'dest': 'v15', 'op': 'div', 'type': 'int'} ,
"eq":{'args': ['sub_0', 'sub_2'], 'dest': 'eq_cond_1', 'op': 'eq', 'type': 'bool'} ,
"lt":{'args': ['sub_0', 'sub_2'], 'dest': 'eq_cond_1', 'op': 'lt', 'type': 'bool'} ,
"gt":{'args': ['sub_0', 'sub_2'], 'dest': 'eq_cond_1', 'op': 'gt', 'type': 'bool'} ,
"le":{'args': ['sub_0', 'sub_2'], 'dest': 'eq_cond_1', 'op': 'le', 'type': 'bool'} ,
"ge":{'args': ['sub_0', 'sub_2'], 'dest': 'eq_cond_1', 'op': 'ge', 'type': 'bool'} ,
"not":{'args': ['x'], 'dest': 'xn', 'op': 'not', 'type': 'bool'} ,
"and":{'args': ['width_check', 'height_check'], 'dest': 'first_check', 'op': 'and', 'type': 'bool'} ,
"or":{'args': ['eq_cond_1', 'eq_cond_2'], 'dest': 'eq_cond_12', 'op': 'or', 'type': 'bool'} ,
"jmp":{'labels': ['l_1_3'], 'op': 'jmp'} ,
"br":{'args': ['cond'], 'labels': ['here', 'there'], 'op': 'br'} ,
"call_noargs":{'dest': 'ab', 'funcs': ['abs'], 'op': 'call', 'type': 'int'} ,
"call_dest":{'args': ['ab'], 'dest': 'ab', 'funcs': ['abs'], 'op': 'call', 'type': 'int'} ,
"call_nodest":{'funcs': ['inner_main'], 'op': 'call'} ,
"ret_arg":{'args': ['a'], 'op': 'ret'} ,
"ret_noarg":{'op': 'ret'} ,
"id":{'args': ['i'], 'dest': 'v10', 'op': 'id', 'type': 'int'} ,
"print":{'args': ['v'], 'op': 'print'} ,
"nop":{'op': 'nop'}
}
